// Code generated by radius-dict-gen. DO NOT EDIT.

package rfc6929

import (
	"layeh.com/radius"
)

const (
	ExtendedAttribute1_Type      radius.Type = 241
	ExtendedAttribute2_Type      radius.Type = 242
	ExtendedAttribute3_Type      radius.Type = 243
	ExtendedAttribute4_Type      radius.Type = 244
	ExtendedAttribute5_Type      radius.Type = 245
	ExtendedAttribute6_Type      radius.Type = 246
	ExtendedVendorSpecific1_Type radius.Type = 241
	ExtendedVendorSpecific2_Type radius.Type = 242
	ExtendedVendorSpecific3_Type radius.Type = 243
	ExtendedVendorSpecific4_Type radius.Type = 244
	ExtendedVendorSpecific5_Type radius.Type = 245
	ExtendedVendorSpecific6_Type radius.Type = 246
)
